[package]
name = "hello-wasi-http"
version = "0.0.0"
edition = "2021"
publish = false

[package.metadata.component]
package = "component:hello-wasi-http"

[package.metadata.component.dependencies]

[package.metadata.component.target]
world = "wasi:http/proxy"
path = "wit/deps/http"

[package.metadata.component.target.dependencies]
"wasi:clocks" = { path = "wit/deps/clocks" }
"wasi:filesystemm" = { path = "wit/deps/filesystem" }
"wasi:sockets" = { path = "wit/deps/sockets" }
"wasi:io" = { path = "wit/deps/io" }
"wasi:random" = { path = "wit/deps/random" }
"wasi:cli" = { path = "wit/deps/cli" }
"wasi:logging" = { path = "wit/deps/logging" }
"wasi:http" = { path = "wit/deps/http" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-component-bindings = "0.3.0"
